form

diff --git a/Prelim/Project - 1C/form b/Prelim/Project - 1C/form
--- a/Prelim/Project - 1C/form
+++ b/Prelim/Project - 1C/form
@@ -1,26 +1,29 @@
 <form method="post">
-    <h3>Basic Information</h3>
-    Fullname: <input type="text" name="name" required><br>
-    Course: <input type="text" name="course" required><br>
-    Level: <input type="number" name="level" required><br>
-    Status: 
-    <select name="status" required>
-        <option value="regular">Regular</option>
-        <option value="irregular">Irregular</option>
+    <h1>Enrollment Form</h1>
+    <strong>Basic Information</strong><br>
+    <input type="text" name="name" placeholder="Fullname"><br>
+    <input type="text" name="course" placeholder="Course"><br>
+    <input type="number" name="level" placeholder="Level"><br>
+    <strong>Status:</strong> 
+    <select name="status">
+        <option value="">- Student Type -</option>
+        <option value="council">Council</option>
+        <option value="scholar">Scholar</option>
+        <option value="working">Working</option>
     </select>
     <br><br>
+    
+    <strong>For Scholars</strong><br>
+    <input type="text" name="program" placeholder="Scholarship Program"><br>
+    <input type="text" name="type" placeholder="Scholarship Type"><br><br>
 
-    <h3>For Scholars</h3>
-    Scholarship Program: <input type="text" name="program"><br>
-    Scholarship Type: <input type="text" name="type"><br><br>
+    <strong>For Student Council</strong><br>
+    <input type="text" name="position" placeholder="Position"> <br>
+    <input type="text" name="org" placeholder="Organization"> <br><br>
 
-    <h3>For Student Council</h3>
-    Position: <input type="text" name="position"> <br>
-    Organization: <input type="text" name="org"> <br><br>
-
-    <h3>For Working Students</h3>
-    Job Title: <input type="text" name="job"> <br>
-    Company: <input type="text" name="company"> <br><br>
+    <strong>For Working Students</strong><br>
+    <input type="text" name="job" placeholder="Job Title"> <br>
+    <input type="text" name="company" placeholder="Company"> <br><br>
     
     <input type="submit" name="submit" value="Enroll Student"><br><br>
 </form>
@@ -29,11 +32,10 @@
 require 'class.php';
 
 if (isset($_POST['submit'])) {
-    $name = $_POST['name'];
+    $fullname = $_POST['name'];
     $course = $_POST['course'];
     $level = $_POST['level'];
     $status = $_POST['status'];
-
     $scholarshipProgram = $_POST['program'];
     $scholarshipType = $_POST['type'];
     $position = $_POST['position'];
@@ -41,35 +43,26 @@ if (isset($_POST['submit'])) {
     $jobTitle = $_POST['job'];
     $company = $_POST['company'];
 
-    if (empty($scholarshipProgram) && empty($position) && empty($jobTitle)) {
-        $response = new Student($name, $course, $level, $status);
+  if (!empty($fullname) && !empty($course) && !empty($level) 
+  && (($status === "working" && !empty($jobTitle) && !empty($company)) 
+  || ($status === "council" && !empty($position) && !empty($organization)) 
+  || ($status === "scholar" && !empty($scholarshipProgram) && !empty($scholarshipType)))) {
 
-    } elseif (!empty($scholarshipProgram) && empty($position) && empty($jobTitle)) {
-        $response = new StudentScholar($name, $course, $level, $status, $scholarshipProgram, $scholarshipType);
-
-    } elseif (empty($scholarshipProgram) && !empty($position) && empty($jobTitle)) {
-        $response = new StudentCouncil($name, $course, $level, $status, $position, $organization);
-
-    } elseif (!empty($scholarshipProgram) && !empty($position) && empty($jobTitle)) {
-        $response = new StudentCouncilScholar($name, $course, $level, $status, $position, $organization, $scholarshipProgram, $scholarshipType);
-
-    } elseif (empty($scholarshipProgram) && empty($position) && !empty($jobTitle)) {
-        $response = new WorkingStudent($name, $course, $level, $status, $jobTitle, $company);
-
-    } elseif (empty($scholarshipProgram) && !empty($position) && !empty($jobTitle)) {
-        $response = new WorkingCouncilStudent($name, $course, $level, $status, $position, $organization, $jobTitle, $company);
-
-    } elseif (!empty($scholarshipProgram) && empty($position) && !empty($jobTitle)) {
-        $response = new WorkingScholarStudent($name, $course, $level, $status, $scholarshipProgram, $scholarshipType, $jobTitle, $company);
-
-    } elseif (!empty($scholarshipProgram) && !empty($position) && !empty($jobTitle)) {
-        $response = new WorkingCouncilScholarStudent($name, $course, $level, $status, $position, $organization, $scholarshipProgram, $scholarshipType, $jobTitle, $company);
-
-    } else {
-        echo "Invalid data input.";
-        exit;
-    }
-
-    echo $response->enrollment();
+  if ($status === "working") {
+    $profile = new WorkingStudent($fullname, $course, $level, $status, $jobTitle, $company);
+    $response = $profile->working();
+  } elseif ($status === "council") {
+    $profile = new StudentCouncil($fullname, $course, $level, $status, $position, $organization);
+    $response = $profile->council();
+  } elseif ($status === "scholar") {
+    $profile = new StudentScholar($fullname, $course, $level, $status, $scholarshipProgram, $scholarshipType);
+    $response = $profile->scholar();
+  }
+  echo $profile->introduction() . "<br>";
+  echo $response . "<br>";
+  echo $profile->enrollment() . "<br>";
+} else {
+  echo "Invalid data input!";
+}
 }
 ?>
